---
- name: Prepare all Kubernetes nodes
  hosts: all
  become: yes
  vars:
    # МЕНЯЕМ ВЕРСИЮ НА 1.30 (1.28 конфликтует с Debian 13)
    k8s_major_version: "v1.30"
    k8s_package_version: "1.30.*"
  
  tasks:
    # --- БЛОК ЛЕЧЕНИЯ DEBIAN 13 ---
    - name: Fix corrupted apt lists (Critical for Debian 13)
      shell: |
        rm -rf /var/lib/apt/lists/*
        apt-get clean
      args:
        warn: false
      ignore_errors: yes

    - name: Update apt cache manually (bypass python-apt module first run)
      shell: apt-get update
      # Игнорируем ошибки, если какой-то репо недоступен, главное оживить базу
      ignore_errors: yes 
    # ------------------------------

    - name: Disable swap (runtime)
      command: swapoff -a
      changed_when: false

    - name: Disable swap (permanent in /etc/fstab)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+.*)$'
        replace: '# \1'

    - name: Create modules-load config
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Load kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Configure sysctl params for Kubernetes
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        sysctl_file: /etc/sysctl.d/k8s.conf
        reload: yes
      loop:
        - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
        - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
        - { name: 'net.ipv4.ip_forward', value: '1' }

    - name: Install required prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          # Добавляем sudo, если его вдруг нет на чистой системе
          - sudo 
        state: present
        update_cache: yes

    # --- Настройка Docker ---
    
    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      apt_repository:
        # Принудительно используем bookworm (Debian 12 stable) для Docker
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable"
        state: present
        filename: docker

    - name: Install containerd
      apt:
        name: containerd.io
        state: present
        update_cache: yes

    - name: Configure containerd default config
      shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Update SystemdCgroup in containerd config
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'
      notify: Restart containerd

    # --- Настройка Kubernetes (НОВЫЙ РЕПОЗИТОРИЙ) ---

    - name: Download Kubernetes GPG key
      shell: |
        # Удаляем старый ключ если был, чтобы не конфликтовать
        rm -f /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ k8s_major_version }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes
      
    - name: Add Kubernetes repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8s_major_version }}/deb/ /"
        state: present
        filename: kubernetes

    - name: Install kubeadm, kubelet, kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes
        allow_downgrade: yes

    - name: Hold Kubernetes packages
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Enable and start kubelet
      systemd:
        name: kubelet
        state: started
        enabled: yes

  handlers:
    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted
