---
- name: Initialize Kubernetes cluster on master node
  hosts: k8s_master
  become: yes
  vars:
    k8s_version: "1.28.5" # Эта переменная теперь используется только в kubeadm-config.yaml
    pod_network_cidr: "10.244.0.0/16" # И эта

  tasks:
    # ------------------ ИЗМЕНЕНИЕ 1: ДОБАВЛЕНА НОВАЯ ЗАДАЧА --------------------
    # Эта задача возьмет ваш шаблон, вставит в него переменные Ansible и скопирует
    # на мастер-ноду как обычный YAML файл.
    - name: Copy kubeadm config to master node
      ansible.builtin.template:
        src: kubeadm-config.yaml.j2  # Имя файла, который вы создали в Шаге 1
        dest: /tmp/kubeadm-config.yaml

    # ------------------ ИЗМЕНЕНИЕ 2: ЗАМЕНЕНА ЗАДАЧА `kubeadm init` -----------
    # Старая задача с длинным списком флагов удалена.
    # Новая задача использует флаг --config, который гораздо мощнее и гибче.
    - name: Initialize cluster with kubeadm using config file
      ansible.builtin.shell:
        # Теперь команда init простая и ссылается на наш конфигурационный файл
        cmd: "kubeadm init --config /tmp/kubeadm-config.yaml --upload-certs"
        # Логика creates остается, чтобы не перезапускать init, если кластер уже создан
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init
      changed_when: kubeadm_init.rc == 0
    # -------------------------------------------------------------------------
      
    - name: Create .kube directory for admin user
      ansible.builtin.file:
        path: /home/admin/.kube
        state: directory
        owner: admin
        group: admin
        mode: '0755'

    - name: Copy admin config to user directory
      ansible.builtin.shell:
        cmd: |
          cp -f /etc/kubernetes/admin.conf /home/admin/.kube/config
          chown admin:admin /home/admin/.kube/config
      changed_when: true

    - name: Extract complete join command from kubeadm output
      ansible.builtin.set_fact:
        join_command: "{{ kubeadm_init.stdout | regex_search('kubeadm join.*') }}"
      when: kubeadm_init.stdout is defined

    - name: Save join command to file
      ansible.builtin.copy:
        content: "{{ join_command }}"
        dest: /tmp/k8s_join_command.txt
        owner: admin
        group: admin
        mode: '0644'
      when: join_command is defined

    - name: Display join command for verification
      ansible.builtin.debug:
        msg: "Join command: {{ join_command }}"
      when: join_command is defined

    - name: Wait for Kubernetes API to be ready
      ansible.builtin.wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: 6443
        delay: 10
        timeout: 120
        state: started

# Этот второй плей в вашем файле я не трогал, он выглядит хорошо.
# Он может остаться как есть.
- name: Configure kubectl for admin user on master
  hosts: k8s_master
  become: yes
  tasks:
    - name: Create .kube directory
      ansible.builtin.file:
        path: /home/admin/.kube
        state: directory
        owner: admin
        group: admin
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/admin/.kube/config
        remote_src: yes
        owner: admin
        group: admin
        mode: '0600'
