---
- name: Initialize Kubernetes cluster on master node
  hosts: k8s_master
  become: yes
  vars:
    k8s_version: "1.28.5"
    pod_network_cidr: "10.244.0.0/16"

  tasks:
    - name: Initialize cluster with kubeadm
      ansible.builtin.shell:
        # Используем cmd и creates для идемпотентности: команда не будет выполняться,
        # если файл admin.conf уже существует.
        cmd: >
          kubeadm init
          --pod-network-cidr {{ pod_network_cidr }}
          --service-cidr 10.96.0.0/12
          --kubernetes-version v{{ k8s_version }}
          --apiserver-advertise-address {{ ansible_default_ipv4.address }}
          --apiserver-cert-extra-sans {{ ansible_hostname }}
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init
      changed_when: kubeadm_init.rc == 0

      
    - name: Create .kube directory for admin user
      ansible.builtin.file:
        path: /home/admin/.kube
        state: directory
        owner: admin
        group: admin
        mode: '0755'

    - name: Copy admin config to user directory
      # Замена shell на модуль copy - более правильный и идемпотентный способ.
      # remote_src: yes указывает, что источник и назначение находятся на удаленной машине.
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/admin/.kube/config
        remote_src: yes
        owner: admin
        group: admin
        mode: '0644'

    - name: Extract complete join command from kubeadm output
      ansible.builtin.set_fact:
        # Этот regex более надежно захватывает всю строку с командой join
        join_command: "{{ kubeadm_init.stdout | regex_search('kubeadm join.*') }}"
      when: kubeadm_init.stdout is defined

    - name: Save join command to file
      ansible.builtin.copy:
        content: "{{ join_command }}"
        dest: /tmp/k8s_join_command.txt
        owner: admin
        group: admin
        mode: '0644'
      when: join_command is defined

    - name: Display join command for verification
      ansible.builtin.debug:
        msg: "Join command: {{ join_command }}"
      when: join_command is defined

    - name: Wait for Kubernetes API to be ready
      ansible.builtin.wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: 6443
        delay: 10
        timeout: 120
        state: started
