- name: Fetch kubeconfig to the control node's shared volume
  hosts: k8s_master
  become: yes # Нужен для чтения /etc/kubernetes/admin.conf

  vars:
    # Этот IP будет использован для замены в kubeconfig
    master_ip: "{{ ansible_default_ipv4.address }}"
    # Путь к файлу в общем томе внутри контейнера semaphore
    shared_config_dest: "/tmp/semaphore/kubeconfig"

  tasks:
    - name: Fetch the kubeconfig file to the Ansible controller
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        # 'dest' здесь - это временный путь на машине, где запущен ansible (т.е. внутри контейнера)
        dest: /tmp/
        flat: yes

    - name: Update server IP in the fetched kubeconfig
      # Эта задача выполняется на localhost (внутри контейнера)
      delegate_to: localhost
      become: no # sudo не нужен для работы с файлами в /tmp
      ansible.builtin.replace:
        # Путь к файлу, который скачал fetch
        path: "/tmp/admin.conf" 
        regexp: 'server: https://.*:6443'
        replace: "server: https://{{ master_ip }}:6443"

    - name: Move the final kubeconfig to the shared volume
      # И снова, эта задача выполняется на localhost (внутри контейнера)
      delegate_to: localhost
      become: no
      ansible.builtin.copy:
        src: "/tmp/admin.conf"
        dest: "{{ shared_config_dest }}"
        mode: '0644' # Устанавливаем права для чтения всем
        remote_src: yes # Указываем, что source - это локальный файл внутри контейнера

    - name: Clean up temporary file on the control node
      delegate_to: localhost
      become: no
      ansible.builtin.file:
        path: "/tmp/admin.conf"
        state: absent
