- name: Install Calico network plugin
  hosts: k8s_master
  become: yes
  tasks:
    tasks:
    - name: Copy correct Calico manifest to master
      ansible.builtin.copy:
        src: calico.yaml  # Наш локальный, исправленный файл
        dest: /tmp/calico.yaml

    - name: Apply the correct Calico manifest
      ansible.builtin.shell:
        cmd: "kubectl apply -f /tmp/calico.yaml"
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
    
    # Паузу можно оставить, она не помешает
    - name: Give Kubernetes a moment to create the pods
      ansible.builtin.pause:
        seconds: 15

    - name: Wait for Calico pods to be ready
      ansible.builtin.shell:
        cmd: "kubectl wait --for=condition=ready pod -l k8s-app=calico-node -n kube-system --timeout=300s"
      environment: # <-- ИСПРАВЛЕНИЕ 2 (НУЖНО ДОБАВИТЬ)
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Wait for all system pods to be ready
      ansible.builtin.shell:
        cmd: "kubectl wait --for=condition=ready pod --all -n kube-system --timeout=300s"
      environment: # <-- ИСПРАВЛЕНИЕ 3 (НУЖНО ДОБАВИТЬ)
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Check cluster status
      ansible.builtin.shell:
        cmd: "kubectl get nodes -o wide"
      environment: # <-- ИСПРАВЛЕНИЕ 4 (НУЖНО ДОБАВИТЬ)
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: cluster_status

    - name: Display cluster status
      ansible.builtin.debug:
        msg: "{{ cluster_status.stdout }}"

    - name: Check system pods
      ansible.builtin.shell:
        cmd: "kubectl get pods -n kube-system"
      environment: # <-- ИСПРАВЛЕНИЕ 5 (НУЖНО ДОБАВИТЬ)
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: system_pods

    - name: Display system pods
      ansible.builtin.debug:
        msg: "{{ system_pods.stdout }}"
