---
- name: Install Calico network plugin
  hosts: k8s_master
  become: yes
  tasks:
    - name: Download and apply Calico manifest
      ansible.builtin.shell: |
        kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml

    - name: Wait for Calico pods to be ready
      ansible.builtin.shell: |
        kubectl wait --for=condition=ready pod -l k8s-app=calico-node -n kube-system --timeout=300s

    - name: Wait for all system pods to be ready
      ansible.builtin.shell: |
        kubectl wait --for=condition=ready pod --all -n kube-system --timeout=300s

    - name: Check cluster status
      ansible.builtin.shell: |
        kubectl get nodes -o wide
      register: cluster_status

    - name: Display cluster status
      ansible.builtin.debug:
        msg: "{{ cluster_status.stdout }}"

    - name: Check system pods
      ansible.builtin.shell: |
        kubectl get pods -n kube-system
      register: system_pods

    - name: Display system pods
      ansible.builtin.debug:
        msg: "{{ system_pods.stdout }}"
