---
- name: Verify Kubernetes cluster functionality
  hosts: k8s_master
  become: yes
  tasks:
    - name: Create test namespace
      ansible.builtin.shell: |
        kubectl create namespace test --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy test nginx application
      ansible.builtin.shell: |
        kubectl create deployment nginx-test --image=nginx:alpine -n test

    - name: Expose deployment as service
      ansible.builtin.shell: |
        kubectl expose deployment nginx-test --port=80 --target-port=80 -n test

    - name: Wait for test pod to be ready
      ansible.builtin.shell: |
        kubectl wait --for=condition=ready pod -l app=nginx-test -n test --timeout=120s

    - name: Check test pod status
      ansible.builtin.shell: |
        kubectl get pods -n test -o wide
      register: test_pods

    - name: Display test pods
      ansible.builtin.debug:
        msg: "{{ test_pods.stdout }}"

    - name: Test service connectivity
      ansible.builtin.shell: |
        kubectl run test-curl --image=curlimages/curl:latest -i --rm --restart=Never -- curl -s http://nginx-test.test:80
      register: curl_test

    - name: Display curl test result
      ansible.builtin.debug:
        msg: "Service test result: {{ curl_test.stdout }}"

    - name: Cleanup test resources
      ansible.builtin.shell: |
        kubectl delete namespace test
