---
- name: My First Ansible Playbook
  hosts: web-servers # Группа из инвентаря
  become: yes      # Выполнять задачи с правами sudo
  tasks:
    - name: Update apt package cache (for Debian)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx package
      ansible.builtin.apt: # Лучше использовать apt вместо общего package для Debian
        name: nginx
        state: present

    - name: Start and Enable Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy index.html
      ansible.builtin.copy:
        content: "<h1>Hello from {{ ansible_hostname }}!</h1>"
        dest: /var/www/html/index.html
