---
- name: Complete Kubernetes Cluster Teardown
  # Целимся на все ноды кластера
  hosts: k8s_master, k8s_workers
  become: yes
  # Игнорируем ошибки, чтобы плейбук продолжал работать,
  # даже если какая-то часть уже была удалена
  ignore_errors: yes

  tasks:
    - name: Reset the cluster state using kubeadm
      ansible.builtin.command: kubeadm reset -f
      changed_when: false # Эта команда всегда меняет состояние, но для нас это не важно

    - name: Stop and disable kubelet service
      ansible.builtin.systemd:
        name: kubelet
        state: stopped
        enabled: no

    - name: Uninstall Kubernetes packages
      ansible.builtin.package:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: absent
        autoremove: yes # Удаляем также и зависимости
        purge: yes      # Удаляем и конфигурационные файлы пакетов

    - name: Remove Kubernetes configuration directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes
        - /var/lib/etcd
        - /etc/cni/net.d
        - /var/lib/kubelet
        - /var/run/kubernetes
        - /var/lib/cni/

    - name: Remove user kubeconfig
      ansible.builtin.file:
        path: /home/admin/.kube # Замените 'admin' на вашего пользователя, если он другой
        state: absent

    - name: Prune all containers, pods, and images (optional, but recommended)
      ansible.builtin.shell: |
        crictl rmp -a -f
        crictl rmi -a -f
      changed_when: false
      
    - name: Final system cleanup
      ansible.builtin.command: apt-get autoremove -y
      changed_when: false
