apiVersion: v2
name: django-app
description: A Django application with PostgreSQL
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    # Обновляем версию чарта с 12.1.0 на 12.12.10 (более стабильная для этой ветки)
    version: "12.12.10"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
